document.getElementById("veg").addEventListener("click",function(){
    window.open("vegmenu.html","_blank");
});
document.getElementById("drinks").addEventListener("click",function(){
    window.open("drinksmenu.html","_blank");
});
document.getElementById("desserts").addEventListener("click",function(){
    window.open("dessertsmenu.html","_blank");
});
