apiVersion: apps/v1
kind: Deployment
metadata:
  name: threebroomsticks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threebroomsticks
  template:
    metadata:
      labels:
        app: threebroomsticks
    spec:
      containers:
      - name: threebroomsticks
        image: tarun2210/threebroomsticks-inn:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: threebroomsticks-service
spec:
  selector:
    app: threebroomsticks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
