apiVersion: apps/v1
kind: Deployment
metadata:
  name: threebroomsticks-deployment
  labels:
    app: threebroomsticks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: threebroomsticks
  template:
    metadata:
      labels:
        app: threebroomsticks
    spec:
      containers:
        - name: threebroomsticks-container
          image: tarun2210/threebroomsticks-inn:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: threebroomsticks-service
spec:
  selector:
    app: threebroomsticks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
