apiVersion: apps/v1
kind: Deployment
metadata:
  name: threebroomsticks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inn
  template:
    metadata:
      labels:
        app: inn
    spec:
      containers:
      - name: inn-container
        image: tarun2210/threebroomsticks-inn:latest
        ports:
        - containerPort: 80
