apiVersion: v1
kind: Service
metadata:
  name: threebroomsticks-service
spec:
  selector:
    app: threebroomsticks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  
  type: LoadBalancer  
