apiVersion: v1
kind: Service
metadata:
  name: threebroomsticks-service
spec:
  selector:
    app: threebroomsticks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Adjust based on your app
  type: LoadBalancer  # Use NodePort if not on cloud (e.g. minikube)
