name: Validate and Deploy

on:
  push:
    branches: [master] 

jobs:
  validate:
    name: Code Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install HTML5 Validator
        run: pip install html5validator

      - name: Validate HTML
        run: html5validator --root . --show-warnings

      - name: Install CSSLint
        run: npm install -g csslint

      - name: Validate CSS
        run: csslint **/*.css || true

  deploy:
    name: Deploy Project
    needs: validate  # Ensures deploy only runs after validate succeeds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: ./deploy.sh  # or whatever your deploy step is
